// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDy4AnVgYzoRH3Ag4DhAy9earoa8024zo',
    appId: '1:1027061698954:web:71f8640e9545af3fe97873',
    messagingSenderId: '1027061698954',
    projectId: 'chatting-app-2c255',
    authDomain: 'chatting-app-2c255.firebaseapp.com',
    storageBucket: 'chatting-app-2c255.appspot.com',
    measurementId: 'G-8HLLTHM1PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_oiZyvIJyh9kNjy_57tbDb64120fV_Q',
    appId: '1:1027061698954:android:bb95946bf479f98fe97873',
    messagingSenderId: '1027061698954',
    projectId: 'chatting-app-2c255',
    storageBucket: 'chatting-app-2c255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-a6Hg93gpxkRNDJn664ijSGaLZl3xmM',
    appId: '1:1027061698954:ios:61afafee09ef2aa3e97873',
    messagingSenderId: '1027061698954',
    projectId: 'chatting-app-2c255',
    storageBucket: 'chatting-app-2c255.appspot.com',
    iosClientId: '1027061698954-ampabnqc2efu1396t1d8grr3r2em2okl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-a6Hg93gpxkRNDJn664ijSGaLZl3xmM',
    appId: '1:1027061698954:ios:80a83e146acd13bee97873',
    messagingSenderId: '1027061698954',
    projectId: 'chatting-app-2c255',
    storageBucket: 'chatting-app-2c255.appspot.com',
    iosClientId: '1027061698954-fv5u7856e8oa7ue5ugv8qifljh6hmivm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
